# Use the official Nginx image as the base image
FROM nginx:latest

# 创建结果目录
RUN mkdir -p /etc/nginx/html && \
    chmod -R 777 /etc/nginx/html

COPY ./data/configure/nginx.conf /etc/nginx/conf.d/pmet.conf

# Expose Nginx's default port
EXPOSE 19258

# Start Nginx service
CMD ["nginx", "-g", "daemon off;"]
